/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ServicosController;
import Model.DAO.Conexao;
import Model.DAO.ServicoDAO;
import Model.Servicos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author breno
 */
public class CadServico extends javax.swing.JFrame {
    private final ServicosController controller;

    /**
     * Creates new form CadServico
     */
    public CadServico() throws SQLException {
        initComponents();
        controller = new ServicosController(this);
        DefaultTableModel modelo = (DefaultTableModel) jTableServico.getModel();
        modelo.setNumRows(0);
        jTableServico.setRowSorter(new TableRowSorter(modelo));
        lerJTable();
        controller.inserirIcone(this);
    }
    
    public void lerJTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) jTableServico.getModel();
        modelo.setNumRows(0);
        Connection conexao = new Conexao().getConnection();
        ServicoDAO servicodao = new ServicoDAO(conexao);
        
        for (Servicos servic: servicodao.ler()) {
            
            modelo.addRow(new Object[]{
                servic.getId(),
                servic.getDescricao(),
                servic.getValor()
            });
            
        }
        
        
    }
    
    public void limparTela() {
        jTextDescricao.setText("");
        jTextValor.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServico = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextValor = new javax.swing.JTextField();
        jButtonExcluirServico = new javax.swing.JButton();
        jButtonEditaServico = new javax.swing.JButton();
        jButtonLimpaServico = new javax.swing.JButton();
        jButtonCadServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Serviços");

        jTableServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRICÃO", "VALOR (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableServicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableServico);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Serviço"));

        jLabel3.setText("Descrição: ");

        jTextDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescricaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor");

        jButtonExcluirServico.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonExcluirServico.setText("Excluir");
        jButtonExcluirServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirServicoActionPerformed(evt);
            }
        });

        jButtonEditaServico.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonEditaServico.setText("Editar");
        jButtonEditaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditaServicoActionPerformed(evt);
            }
        });

        jButtonLimpaServico.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonLimpaServico.setText("Limpar");
        jButtonLimpaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpaServicoActionPerformed(evt);
            }
        });

        jButtonCadServico.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonCadServico.setText("Cadastrar");
        jButtonCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextValor, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(362, 362, 362))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButtonCadServico, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButtonExcluirServico, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButtonEditaServico, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButtonLimpaServico, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluirServico)
                    .addComponent(jButtonEditaServico)
                    .addComponent(jButtonLimpaServico)
                    .addComponent(jButtonCadServico))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescricaoActionPerformed

    private void jButtonEditaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditaServicoActionPerformed
         if(jTableServico.getSelectedRow() != -1) { //Verificando se esta selecionando a linha
        
           //controller.atualizaCliente();
           //String teste = jTableClientes2.getValueAt(jTableClientes2.getSelectedRow(), 2).toString();
           
        String descricao = getjTextDescricao().getText(); //Tive que criar getter e setter pra poder acessar os campos da view
        String valorString = getjTextValor().getText();
        Float valor = Float.parseFloat(valorString);
        int id = ((int)jTableServico.getValueAt(jTableServico.getSelectedRow(), 0));

        
        Servicos servico = new Servicos(id, descricao, valor);
       
       
        try {
            Connection conexao = new Conexao().getConnection();
            ServicoDAO servicodao = new ServicoDAO(conexao);
            servicodao.update(servico);
            
            JOptionPane.showMessageDialog(null, "Serviço Atualizado!");
            
        } catch (SQLException ex) {
            //Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao atualizar!"+ex);
        }
             try {
                 lerJTable();
             } catch (SQLException ex) {
                 Logger.getLogger(CadServico.class.getName()).log(Level.SEVERE, null, ex);
             }
       }
    }//GEN-LAST:event_jButtonEditaServicoActionPerformed

    private void jButtonExcluirServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirServicoActionPerformed
        if(jTableServico.getSelectedRow() != -1) { //Verificando se esta selecionando a linha
        
           //controller.atualizaCliente();
           //String teste = jTableClientes2.getValueAt(jTableClientes2.getSelectedRow(), 2).toString();
           
        String descricao = getjTextDescricao().getText(); //Tive que criar getter e setter pra poder acessar os campos da view
        String valorString = getjTextValor().getText();
        Float valor = Float.parseFloat(valorString);
        int id = ((int)jTableServico.getValueAt(jTableServico.getSelectedRow(), 0));

        
        Servicos servico = new Servicos(id, descricao, valor);
       
       
        try {
            Connection conexao = new Conexao().getConnection();
            ServicoDAO servicodao = new ServicoDAO(conexao);
            servicodao.delete(servico);
            
            JOptionPane.showMessageDialog(null, "Serviço Deletado!");
            
        } catch (SQLException ex) {
            //Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,  "Erro ao excluir!\nExistem agendamentos com este tipo de serviço!");
            
           
        }
             try {
                 lerJTable();
             } catch (SQLException ex) {
                 Logger.getLogger(CadServico.class.getName()).log(Level.SEVERE, null, ex);
             }
       }
        limparTela();
    }//GEN-LAST:event_jButtonExcluirServicoActionPerformed

    private void jTableServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableServicoMouseClicked
         if(jTableServico.getSelectedRow() != -1) {
        
        jTextDescricao.setText(jTableServico.getValueAt(jTableServico.getSelectedRow(), 1).toString());
        jTextValor.setText(jTableServico.getValueAt(jTableServico.getSelectedRow(), 2).toString());
       
        
        
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }
    }//GEN-LAST:event_jTableServicoMouseClicked

    private void jButtonLimpaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpaServicoActionPerformed
        limparTela();
    }//GEN-LAST:event_jButtonLimpaServicoActionPerformed

    private void jButtonCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadServicoActionPerformed
        controller.salvaServicos();
        limparTela();
        try {
            lerJTable();
        } catch (SQLException ex) {
            Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadServico().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadServico.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JTextField getjTextDescricao() {
        return jTextDescricao;
    }

    public void setjTextDescricao(JTextField jTextDescricao) {
        this.jTextDescricao = jTextDescricao;
    }

  
    public JTextField getjTextValor() {
        return jTextValor;
    }

    public void setjTextValor(JTextField jTextValor) {
        this.jTextValor = jTextValor;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadServico;
    private javax.swing.JButton jButtonEditaServico;
    private javax.swing.JButton jButtonExcluirServico;
    private javax.swing.JButton jButtonLimpaServico;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServico;
    private javax.swing.JTextField jTextDescricao;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables

  
}
