/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.menuprincipalController;
import Model.Cliente;
import Model.DAO.ClienteDAO;
import Model.DAO.Conexao;
import Model.DAO.ServicoDAO;
import Model.Servicos;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author breno
 */
public class menuprincipal extends javax.swing.JFrame {
    private final menuprincipalController controller;

    /**
     * Creates new form menuprincipal
     */
    public menuprincipal() {
        initComponents();
        this.controller = new menuprincipalController(this);
        controller.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemServiço = new javax.swing.JMenuItem();
        jMenuItemEstoque = new javax.swing.JMenuItem();
        jMenuItemAgendamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRelCliente = new javax.swing.JMenuItem();
        jMenuItemRelServiço = new javax.swing.JMenuItem();
        jMenuItemRelEstoque = new javax.swing.JMenuItem();
        jMenuItemRelLucro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AlphaLogoRed2.jpg"))); // NOI18N
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jMenuBar1.setToolTipText("");

        jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItemCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/cliente32-icon.png"))); // NOI18N
        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCliente);

        jMenuItemServiço.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemServiço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/ferramenta.png"))); // NOI18N
        jMenuItemServiço.setText("Serviço");
        jMenuItemServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServiçoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemServiço);

        jMenuItemEstoque.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/estoque.png"))); // NOI18N
        jMenuItemEstoque.setText("Estoque");
        jMenuItemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstoqueActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemEstoque);

        jMenuItemAgendamento.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/agenda32-icon.png"))); // NOI18N
        jMenuItemAgendamento.setText("Agendamento");
        jMenuItemAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendamentoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemAgendamento);

        jMenuBar1.add(jMenuCadastro);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Relatórios");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItemRelCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemRelCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/customer-service.png"))); // NOI18N
        jMenuItemRelCliente.setText("Clientes");
        jMenuItemRelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRelCliente);

        jMenuItemRelServiço.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemRelServiço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/cronograma.png"))); // NOI18N
        jMenuItemRelServiço.setText("Agendamentos");
        jMenuItemRelServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelServiçoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRelServiço);

        jMenuItemRelEstoque.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemRelEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/caixa-de-ferramentas (1).png"))); // NOI18N
        jMenuItemRelEstoque.setText("Servicos");
        jMenuItemRelEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelEstoqueActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRelEstoque);

        jMenuItemRelLucro.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItemRelLucro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/ferramenta.png"))); // NOI18N
        jMenuItemRelLucro.setText("Estoque");
        jMenuItemRelLucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelLucroActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRelLucro);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1318, 935));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelClienteActionPerformed
       try {
            controller.navegarParaRelatorioCliente();
        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemRelClienteActionPerformed

    private void jMenuItemRelLucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelLucroActionPerformed
        try {
            controller.navegarParaRelatorioPeca();
        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemRelLucroActionPerformed

    private void jMenuItemServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServiçoActionPerformed
        try {
            controller.navegarParaCadastroServico();
            
            } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            /*try {
            Connection conexao = new Conexao().getConnection();  //abrindo conexao
            ServicoDAO servicoDao = new ServicoDAO(conexao);
            
            
            Servicos servicoInsert = new Servicos("servicoteste", 7);
            Servicos servicoInserido = servicoDao.insert(servicoInsert);
            
            
            //select id
            
            Servicos servicoSelecionado = servicoDao.selectPorId(servicoInserido);
            
            //delete
            servicoDao.delete(servicoSelecionado);
            
            //selecall
            ArrayList<Servicos> servicos = servicoDao.selectAll();  //Cria a lista
            
            for (Servicos servico : servicos) {  //cria variavel servico, pega o servicos(lista) joga um servico(lisa) dentro da variavel servico e trabalha dentro da chave, loop
            System.out.println(""+servico.getDescricao());
            }
            
            } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        
    }//GEN-LAST:event_jMenuItemServiçoActionPerformed

    private void jMenuItemAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendamentoActionPerformed
        try {
            controller.navegarParaAgendamento();
        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemAgendamentoActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        try {
            controller.navegarParaCadastroCliente();
        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemRelServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelServiçoActionPerformed
        try {
            controller.navegarParaRelatorioAgendamento();
        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemRelServiçoActionPerformed

    private void jMenuItemRelEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelEstoqueActionPerformed
        try {
            controller.navegarParaRelatorioServico();
        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemRelEstoqueActionPerformed

    private void jMenuItemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstoqueActionPerformed
        try {
            controller.navegarParaCadastroPeca();
        } catch (SQLException ex) {
            Logger.getLogger(menuprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemEstoqueActionPerformed

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemAgendamento;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemEstoque;
    private javax.swing.JMenuItem jMenuItemRelCliente;
    private javax.swing.JMenuItem jMenuItemRelEstoque;
    private javax.swing.JMenuItem jMenuItemRelLucro;
    private javax.swing.JMenuItem jMenuItemRelServiço;
    private javax.swing.JMenuItem jMenuItemServiço;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
