/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.PecaController;
import Model.DAO.Conexao;
import Model.DAO.PecaDAO;
import Model.Peca;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author breno
 */
public class TelEstoque extends javax.swing.JFrame {
    private final PecaController controller;

    /**
     * Creates new form TelEstoque
     */
    public TelEstoque() throws SQLException {
        initComponents();
        controller = new PecaController(this);
        DefaultTableModel modelo = (DefaultTableModel) jTablePeca.getModel();
        modelo.setNumRows(0);
        jTablePeca.setRowSorter(new TableRowSorter(modelo));
        lerJTable();
        controller.inserirIcone(this);
    }
    
    public void lerJTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) jTablePeca.getModel();
        modelo.setNumRows(0);
        Connection conexao = new Conexao().getConnection();
        PecaDAO pecadao = new PecaDAO(conexao);
        
        for (Peca pec: pecadao.ler()) {
            
            modelo.addRow(new Object[]{
                pec.getId(),
                pec.getDescricao(),
                pec.getMarca(),
                pec.getValor(),
                pec.getQtd()
            });
            
        }
        
        
    }
    
    public void limparTela() {
        jTextDescEstoque.setText("");
        jTextMarcaEstoque.setText("");
        jTextValorEstoque.setText("");
        jTextQtd.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextQtd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePeca = new javax.swing.JTable();
        jTextValorEstoque = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextMarcaEstoque = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextDescEstoque = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonCadastrarEstoque = new javax.swing.JButton();
        jButtonExcluirEstoque = new javax.swing.JButton();
        jButtonEditarEstoque = new javax.swing.JButton();
        jButtonLimparEstoque = new javax.swing.JButton();

        jLabel3.setBackground(new java.awt.Color(51, 255, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Peças");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Quantidade");

        jTextQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQtdActionPerformed(evt);
            }
        });

        jTablePeca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRICÃO", "MARCA", "VALOR", "QUANTIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePecaMouseClicked(evt);
            }
        });
        jTablePeca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTablePecaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePeca);

        jTextValorEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValorEstoqueActionPerformed(evt);
            }
        });

        jLabel7.setText("Valor");

        jLabel6.setText("Marca");

        jTextMarcaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMarcaEstoqueActionPerformed(evt);
            }
        });

        jLabel5.setText("Descrição");

        jTextDescEstoque.setMaximumSize(new java.awt.Dimension(500000000, 500000000));
        jTextDescEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescEstoqueActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 50000));

        jButtonCadastrarEstoque.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonCadastrarEstoque.setText("Cadastrar");
        jButtonCadastrarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarEstoqueActionPerformed(evt);
            }
        });

        jButtonExcluirEstoque.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonExcluirEstoque.setText("Excluir");
        jButtonExcluirEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEstoqueActionPerformed(evt);
            }
        });

        jButtonEditarEstoque.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonEditarEstoque.setText("Editar");
        jButtonEditarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarEstoqueActionPerformed(evt);
            }
        });

        jButtonLimparEstoque.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonLimparEstoque.setText("Limpar");
        jButtonLimparEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonCadastrarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluirEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonEditarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButtonLimparEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarEstoque)
                    .addComponent(jButtonExcluirEstoque)
                    .addComponent(jButtonEditarEstoque)
                    .addComponent(jButtonLimparEstoque))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDescEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextMarcaEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValorEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextQtd, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(175, 175, 175))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(4, 4, 4)
                                .addComponent(jTextDescEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(4, 4, 4)
                                .addComponent(jTextMarcaEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(4, 4, 4)
                                .addComponent(jTextValorEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextDescEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescEstoqueActionPerformed

    private void jTextMarcaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMarcaEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMarcaEstoqueActionPerformed

    private void jTextValorEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValorEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValorEstoqueActionPerformed

    private void jButtonEditarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarEstoqueActionPerformed
          if(jTablePeca.getSelectedRow() != -1) { //Verificando se esta selecionando a linha
        
           //controller.atualizaCliente();
           //String teste = jTableClientes2.getValueAt(jTableClientes2.getSelectedRow(), 2).toString();
           
        String descricao = getjTextDescEstoque().getText(); //Tive que criar getter e setter pra poder acessar os campos da view
        String marca = getjTextMarcaEstoque().getText();
        String valorString = getjTextValorEstoque().getText();
        Float valor = Float.parseFloat(valorString);
        int id = ((int)jTablePeca.getValueAt(jTablePeca.getSelectedRow(), 0));
        String qtdString = getjTextQtd().getText();
        int qtd = Integer.parseInt(qtdString);

        
        Peca peca = new Peca(id, descricao, marca, valor, qtd);
       
       
        try {
            Connection conexao = new Conexao().getConnection();
            PecaDAO servicodao = new PecaDAO(conexao);
            servicodao.update(peca);
            
            JOptionPane.showMessageDialog(null, "Serviço Atualizado!");
            
        } catch (SQLException ex) {
            //Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao atualizar!"+ex);
        }
              try {
                  lerJTable();
              } catch (SQLException ex) {
                  Logger.getLogger(TelEstoque.class.getName()).log(Level.SEVERE, null, ex);
              }
       }
          limparTela();
    }//GEN-LAST:event_jButtonEditarEstoqueActionPerformed

    public JButton getjButtonEditarEstoque() {
        return jButtonEditarEstoque;
    }

    public void setjButtonEditarEstoque(JButton jButtonEditarEstoque) {
        this.jButtonEditarEstoque = jButtonEditarEstoque;
    }

    public JButton getjButtonExcluirEstoque() {
        return jButtonExcluirEstoque;
    }

    public void setjButtonExcluirEstoque(JButton jButtonExcluirEstoque) {
        this.jButtonExcluirEstoque = jButtonExcluirEstoque;
    }



    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

 

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JTextField getjTextQtd() {
        return jTextQtd;
    }

    public void setjTextQtd(JTextField jTextQtd) {
        this.jTextQtd = jTextQtd;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjTablePeca() {
        return jTablePeca;
    }

    public void setjTablePeca(JTable jTablePeca) {
        this.jTablePeca = jTablePeca;
    }

    private void jButtonExcluirEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEstoqueActionPerformed
        if(jTablePeca.getSelectedRow() != -1) { //Verificando se esta selecionando a linha
        
           //controller.atualizaCliente();
           //String teste = jTableClientes2.getValueAt(jTableClientes2.getSelectedRow(), 2).toString();
           
        String descricao = getjTextDescEstoque().getText(); //Tive que criar getter e setter pra poder acessar os campos da view
        String marca = getjTextMarcaEstoque().getText();
        String valorString = getjTextValorEstoque().getText();
        Float valor = Float.parseFloat(valorString);
        int id = ((int)jTablePeca.getValueAt(jTablePeca.getSelectedRow(), 0));
        String qtdString = getjTextQtd().getText();
        int qtd = Integer.parseInt(qtdString);

        
        Peca peca = new Peca(id, descricao, marca, valor, qtd);
       
       
        try {
            Connection conexao = new Conexao().getConnection();
            PecaDAO servicodao = new PecaDAO(conexao);
            servicodao.delete(peca);
            
            JOptionPane.showMessageDialog(null, "Serviço excluído!");
            
        } catch (SQLException ex) {
            //Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,  "Erro ao excluir!\nExiste esse tipo de peça vinculada em Agendamentos!");
            
        }
              try {
                  lerJTable();
              } catch (SQLException ex) {
                  Logger.getLogger(TelEstoque.class.getName()).log(Level.SEVERE, null, ex);
              }
       }
        limparTela();
    }//GEN-LAST:event_jButtonExcluirEstoqueActionPerformed

    private void jTablePecaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePecaKeyReleased
         
    }//GEN-LAST:event_jTablePecaKeyReleased

    private void jTablePecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePecaMouseClicked
        if(jTablePeca.getSelectedRow() != -1) {
      
        jTextDescEstoque.setText(jTablePeca.getValueAt(jTablePeca.getSelectedRow(), 1).toString());
        jTextMarcaEstoque.setText(jTablePeca.getValueAt(jTablePeca.getSelectedRow(), 2).toString());
        jTextValorEstoque.setText(jTablePeca.getValueAt(jTablePeca.getSelectedRow(), 3).toString());
        jTextQtd.setText(jTablePeca.getValueAt(jTablePeca.getSelectedRow(), 4).toString());
        
        
      
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto");
        }
    }//GEN-LAST:event_jTablePecaMouseClicked

    private void jButtonLimparEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparEstoqueActionPerformed
        limparTela();
    }//GEN-LAST:event_jButtonLimparEstoqueActionPerformed

    private void jTextQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQtdActionPerformed

    private void jButtonCadastrarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarEstoqueActionPerformed
        controller.salvaPeca();
        limparTela();
        try {
            lerJTable();
        } catch (SQLException ex) {
            Logger.getLogger(TelEstoque.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCadastrarEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelEstoque().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelEstoque.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JButton getjButtonCadastrarEstoque() {
        return jButtonCadastrarEstoque;
    }

    public void setjButtonCadastrarEstoque(JButton jButtonCadastrarEstoque) {
        this.jButtonCadastrarEstoque = jButtonCadastrarEstoque;
    }

    public JTextField getjTextDescEstoque() {
        return jTextDescEstoque;
    }

    public void setjTextDescEstoque(JTextField jTextDescEstoque) {
        this.jTextDescEstoque = jTextDescEstoque;
    }



    public JTextField getjTextMarcaEstoque() {
        return jTextMarcaEstoque;
    }

    public void setjTextMarcaEsoque(JTextField jTextMarcaEsoque) {
        this.jTextMarcaEstoque = jTextMarcaEsoque;
    }

    public JTextField getjTextValorEstoque() {
        return jTextValorEstoque;
    }

    public void setjTextValorEstoque(JTextField jTextValorEstoque) {
        this.jTextValorEstoque = jTextValorEstoque;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarEstoque;
    private javax.swing.JButton jButtonEditarEstoque;
    private javax.swing.JButton jButtonExcluirEstoque;
    private javax.swing.JButton jButtonLimparEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePeca;
    private javax.swing.JTextField jTextDescEstoque;
    private javax.swing.JTextField jTextMarcaEstoque;
    private javax.swing.JTextField jTextQtd;
    private javax.swing.JTextField jTextValorEstoque;
    // End of variables declaration//GEN-END:variables

 
}
